"""
╔══════════════════════════════════════════════════════════════════╗
║           HoneyShield — Intrusion Analysis Module                ║
║  Covers all 7 project modules:                                   ║
║   1. Honeypot Service Module                                     ║
║   2. Request Capture Module                                      ║
║   3. Intrusion Logging Module                                    ║
║   4. Intrusion Analysis Module                                   ║
║   5. Alert Generation Module                                     ║
║   6. Dashboard Module                                            ║
║   7. Database Management Module                                  ║
╚══════════════════════════════════════════════════════════════════╝
"""

import os
import socket
import threading
import random
import json
from datetime import datetime, timedelta
from collections import Counter, defaultdict

from flask import Flask, render_template, jsonify, request, redirect, url_for
from flask_sqlalchemy import SQLAlchemy


# ══════════════════════════════════════════════════════════════════
# APP & DATABASE SETUP
# ══════════════════════════════════════════════════════════════════

app = Flask(__name__, template_folder="templates")

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{os.path.join(BASE_DIR, 'honeyshield.db')}"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["SECRET_KEY"] = "honeyshield-secret-2026"

db = SQLAlchemy(app)


# ══════════════════════════════════════════════════════════════════
# MODULE 7 — DATABASE MANAGEMENT MODULE
# ORM models for all intrusion records and alerts
# ══════════════════════════════════════════════════════════════════

class IntrusionLog(db.Model):
    """
    Stores every captured intrusion attempt.
    Populated by the Request Capture Module and
    persisted by the Intrusion Logging Module.
    """
    __tablename__ = "intrusion_logs"

    id            = db.Column(db.Integer, primary_key=True)
    timestamp     = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    ip_address    = db.Column(db.String(45), nullable=False, index=True)
    port          = db.Column(db.Integer, nullable=True)
    protocol      = db.Column(db.String(10), default="TCP")
    service       = db.Column(db.String(20), default="HTTP")   # SSH / HTTP / FTP
    method        = db.Column(db.String(10), default="GET")
    path          = db.Column(db.String(512), nullable=True)
    payload       = db.Column(db.Text, nullable=True)
    country       = db.Column(db.String(64), nullable=True)
    threat_type   = db.Column(db.String(50), nullable=True)    # SQLi / Brute / etc.
    severity      = db.Column(db.String(10), default="medium") # critical/high/medium/low
    action_taken  = db.Column(db.String(20), default="Logged") # Blocked / Alerted / Logged
    is_blocked    = db.Column(db.Boolean, default=False)
    user_agent    = db.Column(db.String(256), nullable=True)
    session_id    = db.Column(db.String(64), nullable=True)    # honeypot session

    def to_dict(self):
        return {
            "id":           self.id,
            "timestamp":    self.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            "ip_address":   self.ip_address,
            "port":         self.port,
            "protocol":     self.protocol,
            "service":      self.service,
            "method":       self.method,
            "path":         self.path,
            "payload":      self.payload,
            "country":      self.country,
            "threat_type":  self.threat_type,
            "severity":     self.severity,
            "action_taken": self.action_taken,
            "is_blocked":   self.is_blocked,
            "user_agent":   self.user_agent,
        }


class Alert(db.Model):
    """
    Alerts generated by the Alert Generation Module
    whenever suspicious patterns are detected.
    """
    __tablename__ = "alerts"

    id          = db.Column(db.Integer, primary_key=True)
    timestamp   = db.Column(db.DateTime, default=datetime.utcnow)
    title       = db.Column(db.String(256), nullable=False)
    description = db.Column(db.Text, nullable=True)
    ip_address  = db.Column(db.String(45), nullable=True)
    severity    = db.Column(db.String(10), default="high")
    threat_type = db.Column(db.String(50), nullable=True)
    is_read     = db.Column(db.Boolean, default=False)
    is_resolved = db.Column(db.Boolean, default=False)

    def to_dict(self):
        return {
            "id":          self.id,
            "timestamp":   self.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            "title":       self.title,
            "description": self.description,
            "ip_address":  self.ip_address,
            "severity":    self.severity,
            "threat_type": self.threat_type,
            "is_read":     self.is_read,
            "is_resolved": self.is_resolved,
        }


class BlockedIP(db.Model):
    """
    IPs permanently blocked by the system or administrator.
    """
    __tablename__ = "blocked_ips"

    id         = db.Column(db.Integer, primary_key=True)
    ip_address = db.Column(db.String(45), unique=True, nullable=False)
    reason     = db.Column(db.String(256), nullable=True)
    blocked_at = db.Column(db.DateTime, default=datetime.utcnow)
    blocked_by = db.Column(db.String(32), default="system")  # system / admin


# ══════════════════════════════════════════════════════════════════
# MODULE 7 — DATABASE MANAGEMENT HELPERS
# Insert / retrieve / delete operations
# ══════════════════════════════════════════════════════════════════

class DatabaseManager:
    """Handles all database CRUD operations."""

    @staticmethod
    def insert_intrusion(data: dict) -> IntrusionLog:
        """Insert a new intrusion record."""
        log = IntrusionLog(**data)
        db.session.add(log)
        db.session.commit()
        return log

    @staticmethod
    def get_all_logs(limit: int = 500) -> list:
        return IntrusionLog.query.order_by(IntrusionLog.timestamp.desc()).limit(limit).all()

    @staticmethod
    def get_logs_last_hours(hours: int = 24) -> list:
        since = datetime.utcnow() - timedelta(hours=hours)
        return IntrusionLog.query.filter(IntrusionLog.timestamp >= since).all()

    @staticmethod
    def get_logs_by_ip(ip: str) -> list:
        return IntrusionLog.query.filter_by(ip_address=ip).order_by(IntrusionLog.timestamp.desc()).all()

    @staticmethod
    def delete_log(log_id: int) -> bool:
        log = IntrusionLog.query.get(log_id)
        if log:
            db.session.delete(log)
            db.session.commit()
            return True
        return False

    @staticmethod
    def block_ip(ip: str, reason: str = "Manual block", by: str = "admin"):
        existing = BlockedIP.query.filter_by(ip_address=ip).first()
        if not existing:
            entry = BlockedIP(ip_address=ip, reason=reason, blocked_by=by)
            db.session.add(entry)
            # mark all logs from this IP as blocked
            IntrusionLog.query.filter_by(ip_address=ip).update({"is_blocked": True, "action_taken": "Blocked"})
            db.session.commit()
        return True

    @staticmethod
    def is_blocked(ip: str) -> bool:
        return BlockedIP.query.filter_by(ip_address=ip).first() is not None

    @staticmethod
    def insert_alert(data: dict) -> Alert:
        alert = Alert(**data)
        db.session.add(alert)
        db.session.commit()
        return alert

    @staticmethod
    def get_unread_alerts() -> list:
        return Alert.query.filter_by(is_read=False).order_by(Alert.timestamp.desc()).all()

    @staticmethod
    def mark_alert_read(alert_id: int):
        alert = Alert.query.get(alert_id)
        if alert:
            alert.is_read = True
            db.session.commit()

    @staticmethod
    def purge_old_logs(days: int = 30):
        """Delete logs older than N days."""
        cutoff = datetime.utcnow() - timedelta(days=days)
        IntrusionLog.query.filter(IntrusionLog.timestamp < cutoff).delete()
        db.session.commit()


# ══════════════════════════════════════════════════════════════════
# MODULE 2 — REQUEST CAPTURE MODULE
# Captures incoming request details (IP, port, path, payload, UA)
# ══════════════════════════════════════════════════════════════════

class RequestCapture:
    """
    Captures all incoming attacker request metadata.
    Called from honeypot routes and real Flask routes.
    """

    # Known malicious payload signatures
    SQLI_PATTERNS    = ["' OR", "1=1", "UNION SELECT", "DROP TABLE", "admin'--", "SLEEP("]
    XSS_PATTERNS     = ["<script>", "onerror=", "javascript:", "onmouseover=", "alert("]
    PATH_PATTERNS    = ["../", "..\\", "/etc/passwd", "/proc/", "cmd.exe", "/bin/bash"]
    SHELL_PATTERNS   = ["wget ", "curl ", ".php?", "exec(", "system(", "passthru("]
    CRED_PATTERNS    = ["/login", "/admin", "/wp-admin", "/auth", "/signin", "/api/token"]
    SCANNER_PATTERNS = ["/wp-", ".env", ".git", "backup", ".zip", "config.php", "phpinfo"]

    @staticmethod
    def classify_threat(path: str, payload: str = "") -> tuple:
        """
        Classify threat type and severity from path + payload.
        Returns (threat_type, severity).
        """
        combined = (path + " " + (payload or "")).upper()

        for p in RequestCapture.SQLI_PATTERNS:
            if p.upper() in combined:
                return ("SQL Injection", "critical")

        for p in RequestCapture.SHELL_PATTERNS:
            if p.upper() in combined:
                return ("Shell Probe", "critical")

        for p in RequestCapture.PATH_PATTERNS:
            if p.upper() in combined:
                return ("Path Traversal", "critical")

        for p in RequestCapture.XSS_PATTERNS:
            if p.upper() in combined:
                return ("XSS Attempt", "high")

        for p in RequestCapture.CRED_PATTERNS:
            if p.upper() in combined:
                return ("Credential Probe", "high")

        for p in RequestCapture.SCANNER_PATTERNS:
            if p.upper() in combined:
                return ("Scanner Probe", "medium")

        return ("Unknown Probe", "low")

    @staticmethod
    def capture_from_flask_request(req) -> dict:
        """
        Extract all relevant fields from a live Flask request object.
        """
        ip      = req.headers.get("X-Forwarded-For", req.remote_addr or "0.0.0.0").split(",")[0].strip()
        path    = req.path
        payload = req.get_data(as_text=True)[:512] or ""
        ua      = req.user_agent.string[:256]

        threat_type, severity = RequestCapture.classify_threat(path, payload)

        return {
            "ip_address":   ip,
            "port":         req.environ.get("SERVER_PORT", 80),
            "protocol":     "HTTPS" if req.is_secure else "HTTP",
            "service":      "HTTP",
            "method":       req.method,
            "path":         path,
            "payload":      payload[:512] if payload else None,
            "user_agent":   ua,
            "threat_type":  threat_type,
            "severity":     severity,
            "action_taken": "Blocked" if severity == "critical" else "Alerted" if severity == "high" else "Logged",
            "is_blocked":   severity == "critical",
        }

    @staticmethod
    def capture_manual(ip: str, port: int, service: str, path: str,
                       payload: str = "", method: str = "GET",
                       country: str = None, protocol: str = "TCP") -> dict:
        """
        Build a capture dict manually (used by honeypot services).
        """
        threat_type, severity = RequestCapture.classify_threat(path, payload)
        return {
            "ip_address":   ip,
            "port":         port,
            "protocol":     protocol,
            "service":      service,
            "method":       method,
            "path":         path,
            "payload":      payload[:512] if payload else None,
            "country":      country,
            "threat_type":  threat_type,
            "severity":     severity,
            "action_taken": "Blocked" if severity == "critical" else "Alerted",
            "is_blocked":   severity == "critical",
        }


# ══════════════════════════════════════════════════════════════════
# MODULE 3 — INTRUSION LOGGING MODULE
# Persists every captured event into the database
# ══════════════════════════════════════════════════════════════════

class IntrusionLogger:
    """
    Records every intrusion attempt to the database.
    All events pass through here before any analysis.
    """

    @staticmethod
    def log(capture_data: dict) -> IntrusionLog:
        """Log one intrusion event. Returns the saved record."""
        log_entry = DatabaseManager.insert_intrusion(capture_data)
        print(f"[LOG] {log_entry.timestamp} | {log_entry.ip_address} | "
              f"{log_entry.threat_type} | {log_entry.severity.upper()}")
        return log_entry

    @staticmethod
    def log_from_request(req) -> IntrusionLog:
        """Convenience: capture + log a Flask request in one call."""
        data = RequestCapture.capture_from_flask_request(req)
        return IntrusionLogger.log(data)


# ══════════════════════════════════════════════════════════════════
# MODULE 1 — HONEYPOT SERVICE MODULE
# Simulates fake SSH / HTTP services to attract attackers
# ══════════════════════════════════════════════════════════════════

class HoneypotService:
    """
    Creates fake network listeners on common ports.
    Any connection attempt is captured and logged.
    Runs in background threads so Flask stays free.
    """

    # Fake SSH banner (mimics OpenSSH)
    SSH_BANNER = b"SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6\r\n"

    # Fake HTTP 200 response (mimics a real login page)
    HTTP_FAKE_RESPONSE = (
        b"HTTP/1.1 200 OK\r\n"
        b"Content-Type: text/html\r\n"
        b"Server: Apache/2.4.52 (Ubuntu)\r\n"
        b"X-Powered-By: PHP/8.1\r\n\r\n"
        b"<html><body><h1>Admin Login</h1>"
        b"<form method='POST'><input name='user'/><input name='pass' type='password'/>"
        b"<button>Login</button></form></body></html>"
    )

    def __init__(self, host: str = "0.0.0.0"):
        self.host    = host
        self.running = False
        self.threads = []

    def _handle_ssh(self, conn, addr):
        """Handle a fake SSH connection."""
        ip, port = addr
        with app.app_context():
            if not DatabaseManager.is_blocked(ip):
                data = RequestCapture.capture_manual(
                    ip=ip, port=22, service="SSH",
                    path="/ssh", payload="SSH handshake attempt",
                    method="CONNECT", protocol="TCP"
                )
                log = IntrusionLogger.log(data)
                AlertGenerator.evaluate(log)
        try:
            conn.send(self.SSH_BANNER)
            conn.recv(256)   # absorb client response
        except Exception:
            pass
        finally:
            conn.close()

    def _handle_http(self, conn, addr):
        """Handle a fake HTTP connection."""
        ip, port = addr
        try:
            raw = conn.recv(2048).decode(errors="ignore")
            lines  = raw.split("\r\n")
            method = "GET"
            path   = "/"
            if lines:
                parts = lines[0].split(" ")
                if len(parts) >= 2:
                    method, path = parts[0], parts[1]
            # grab body if POST
            body = raw.split("\r\n\r\n", 1)[1][:512] if "\r\n\r\n" in raw else ""
        except Exception:
            method, path, body = "GET", "/", ""
        finally:
            with app.app_context():
                if not DatabaseManager.is_blocked(ip):
                    data = RequestCapture.capture_manual(
                        ip=ip, port=8080, service="HTTP-Honeypot",
                        path=path, payload=body,
                        method=method, protocol="HTTP"
                    )
                    log = IntrusionLogger.log(data)
                    AlertGenerator.evaluate(log)
            try:
                conn.send(self.HTTP_FAKE_RESPONSE)
            except Exception:
                pass
            conn.close()

    def _listen(self, port: int, handler):
        """Generic TCP listener loop."""
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            sock.bind((self.host, port))
            sock.listen(10)
            sock.settimeout(1.0)
            print(f"[HONEYPOT] Listening on port {port}")
            while self.running:
                try:
                    conn, addr = sock.accept()
                    t = threading.Thread(target=handler, args=(conn, addr), daemon=True)
                    t.start()
                except socket.timeout:
                    continue
        except Exception as e:
            print(f"[HONEYPOT] Port {port} error: {e}")

    def start(self, ssh_port: int = 2222, http_port: int = 8080):
        """Start honeypot listeners in background threads."""
        self.running = True
        for port, handler in [(ssh_port, self._handle_ssh), (http_port, self._handle_http)]:
            t = threading.Thread(target=self._listen, args=(port, handler), daemon=True)
            t.start()
            self.threads.append(t)
        print(f"[HONEYPOT] Services active on ports {ssh_port} (SSH) and {http_port} (HTTP)")

    def stop(self):
        self.running = False
        print("[HONEYPOT] Stopped.")


# ══════════════════════════════════════════════════════════════════
# MODULE 5 — ALERT GENERATION MODULE
# Generates alerts when suspicious patterns are detected
# ══════════════════════════════════════════════════════════════════

class AlertGenerator:
    """
    Evaluates each intrusion log and fires alerts when
    thresholds or patterns indicate real threat activity.
    """

    # How many hits from one IP in 10 minutes triggers brute-force alert
    BRUTE_FORCE_THRESHOLD = 10
    # How many criticals from one IP in 1 hour triggers escalation
    CRITICAL_THRESHOLD    = 3

    @staticmethod
    def evaluate(log: IntrusionLog):
        """
        Called after every logged event.
        Checks rules and inserts Alert records if triggered.
        """
        AlertGenerator._check_severity(log)
        AlertGenerator._check_brute_force(log)
        AlertGenerator._check_critical_repeat(log)

    @staticmethod
    def _check_severity(log: IntrusionLog):
        """Immediately alert on Critical events."""
        if log.severity == "critical":
            DatabaseManager.insert_alert({
                "title":       f"Critical threat detected — {log.threat_type}",
                "description": (
                    f"IP {log.ip_address} attempted {log.threat_type} on {log.path}. "
                    f"Action: {log.action_taken}."
                ),
                "ip_address":  log.ip_address,
                "severity":    "critical",
                "threat_type": log.threat_type,
            })
            print(f"[ALERT] CRITICAL — {log.ip_address} — {log.threat_type}")

    @staticmethod
    def _check_brute_force(log: IntrusionLog):
        """
        Alert if the same IP has hit 10+ times in the last 10 minutes.
        Classic brute-force or credential-stuffing pattern.
        """
        window = datetime.utcnow() - timedelta(minutes=10)
        count  = IntrusionLog.query.filter(
            IntrusionLog.ip_address == log.ip_address,
            IntrusionLog.timestamp  >= window
        ).count()

        if count == AlertGenerator.BRUTE_FORCE_THRESHOLD:
            DatabaseManager.insert_alert({
                "title":       f"Brute force pattern — {log.ip_address}",
                "description": (
                    f"IP {log.ip_address} made {count} requests in the last 10 minutes. "
                    f"Possible brute-force or automated scanner."
                ),
                "ip_address":  log.ip_address,
                "severity":    "high",
                "threat_type": "Brute Force",
            })
            print(f"[ALERT] BRUTE FORCE — {log.ip_address} ({count} hits / 10 min)")

    @staticmethod
    def _check_critical_repeat(log: IntrusionLog):
        """
        Alert if same IP generates 3+ critical events in 1 hour.
        Signals a persistent, targeted attacker.
        """
        window = datetime.utcnow() - timedelta(hours=1)
        count  = IntrusionLog.query.filter(
            IntrusionLog.ip_address == log.ip_address,
            IntrusionLog.severity   == "critical",
            IntrusionLog.timestamp  >= window
        ).count()

        if count == AlertGenerator.CRITICAL_THRESHOLD:
            DatabaseManager.insert_alert({
                "title":       f"Persistent attacker — {log.ip_address}",
                "description": (
                    f"IP {log.ip_address} has triggered {count} critical events in the last hour. "
                    f"Recommend immediate block."
                ),
                "ip_address":  log.ip_address,
                "severity":    "critical",
                "threat_type": "Persistent Attack",
            })
            # Auto-block persistent attackers
            DatabaseManager.block_ip(log.ip_address, reason="Auto-blocked: 3+ criticals in 1h", by="system")
            print(f"[ALERT] PERSISTENT ATTACKER auto-blocked — {log.ip_address}")


# ══════════════════════════════════════════════════════════════════
# MODULE 4 — INTRUSION ANALYSIS MODULE
# Detects patterns, calculates risk score, builds statistics
# ══════════════════════════════════════════════════════════════════

class IntrusionAnalyzer:
    """
    Core analysis engine. Processes logged intrusions to
    produce statistics, patterns, risk scores, and trends.
    """

    @staticmethod
    def get_summary(hours: int = 24) -> dict:
        """High-level stats for the dashboard stat cards."""
        logs       = DatabaseManager.get_logs_last_hours(hours)
        total      = len(logs)
        blocked    = sum(1 for l in logs if l.is_blocked)
        unique_ips = len({l.ip_address for l in logs})
        criticals  = sum(1 for l in logs if l.severity == "critical")

        return {
            "total_intrusions": total,
            "unique_attackers":  unique_ips,
            "blocked_requests":  blocked,
            "block_rate":        round(blocked / total * 100, 1) if total else 0,
            "critical_events":   criticals,
            "risk_score":        IntrusionAnalyzer.calculate_risk_score(logs),
        }

    @staticmethod
    def calculate_risk_score(logs: list) -> int:
        """
        0–100 risk score based on:
          - Volume of critical events (weight 40)
          - Unique attacker IPs      (weight 25)
          - Attack frequency         (weight 20)
          - Percentage blocked       (weight 15)
        """
        if not logs:
            return 0

        total     = len(logs)
        criticals = sum(1 for l in logs if l.severity == "critical")
        unique    = len({l.ip_address for l in logs})
        blocked   = sum(1 for l in logs if l.is_blocked)
        block_pct = (blocked / total) if total else 0

        score = (
            min(criticals / max(total, 1) * 100, 100) * 0.40 +
            min(unique / 50, 1) * 100                 * 0.25 +
            min(total / 200, 1) * 100                 * 0.20 +
            (1 - block_pct) * 100                     * 0.15
        )
        return round(min(score, 100))

    @staticmethod
    def get_risk_label(score: int) -> str:
        if score >= 80: return "CRITICAL RISK"
        if score >= 60: return "HIGH RISK"
        if score >= 40: return "MEDIUM RISK"
        return "LOW RISK"

    @staticmethod
    def threat_type_distribution(logs: list) -> list:
        """Count of each threat type — for donut/bar chart."""
        counter = Counter(l.threat_type or "Unknown" for l in logs)
        total   = sum(counter.values()) or 1
        return [
            {"type": t, "count": c, "pct": round(c / total * 100, 1)}
            for t, c in counter.most_common()
        ]

    @staticmethod
    def top_attacker_ips(logs: list, limit: int = 10) -> list:
        """Top IPs by hit count with their dominant threat type."""
        ip_counter    = Counter(l.ip_address for l in logs)
        ip_threat_map = defaultdict(Counter)
        ip_sev_map    = defaultdict(list)
        ip_country    = {}

        for l in logs:
            ip_threat_map[l.ip_address][l.threat_type or "Unknown"] += 1
            ip_sev_map[l.ip_address].append(l.severity)
            if l.country:
                ip_country[l.ip_address] = l.country

        result = []
        for ip, count in ip_counter.most_common(limit):
            dominant_type = ip_threat_map[ip].most_common(1)[0][0]
            sevs          = ip_sev_map[ip]
            # worst severity this IP produced
            sev_order     = ["critical", "high", "medium", "low"]
            worst_sev     = next((s for s in sev_order if s in sevs), "low")
            result.append({
                "ip":       ip,
                "hits":     count,
                "country":  ip_country.get(ip, "Unknown"),
                "type":     dominant_type,
                "severity": worst_sev,
                "blocked":  DatabaseManager.is_blocked(ip),
            })
        return result

    @staticmethod
    def hourly_heatmap(logs: list) -> list:
        """
        Returns a 24-element list of event counts per hour
        for the last 24 hours — used by the heatmap widget.
        """
        counts = [0] * 24
        for l in logs:
            counts[l.timestamp.hour] += 1
        return counts

    @staticmethod
    def recent_events(logs: list, limit: int = 12) -> list:
        """Latest N events for the timeline panel."""
        sorted_logs = sorted(logs, key=lambda l: l.timestamp, reverse=True)
        return [l.to_dict() for l in sorted_logs[:limit]]

    @staticmethod
    def detect_patterns(logs: list) -> list:
        """
        Detect behavioural patterns across all logs.
        Returns a list of human-readable insight strings.
        """
        insights = []
        if not logs:
            return insights

        ip_counter = Counter(l.ip_address for l in logs)
        top_ip, top_count = ip_counter.most_common(1)[0]
        if top_count >= 20:
            insights.append({
                "level":   "danger",
                "title":   f"Heavy attacker: {top_ip}",
                "message": f"Single IP responsible for {top_count} events. Consider immediate block.",
            })

        type_counter = Counter(l.threat_type for l in logs)
        dominant_type, dom_count = type_counter.most_common(1)[0]
        total = len(logs)
        if dom_count / total > 0.4:
            insights.append({
                "level":   "warning",
                "title":   f"Dominant attack type: {dominant_type}",
                "message": f"{dom_count} of {total} events ({round(dom_count/total*100)}%) are {dominant_type}.",
            })

        recent = [l for l in logs if l.timestamp >= datetime.utcnow() - timedelta(hours=1)]
        if len(recent) > 50:
            insights.append({
                "level":   "danger",
                "title":   "Traffic spike detected",
                "message": f"{len(recent)} events in the last hour — possible DDoS or automated scan.",
            })

        criticals = [l for l in logs if l.severity == "critical"]
        if criticals:
            crit_ips = {l.ip_address for l in criticals}
            insights.append({
                "level":   "danger",
                "title":   f"{len(criticals)} critical events from {len(crit_ips)} IP(s)",
                "message": "Immediate review recommended.",
            })

        block_rate = sum(1 for l in logs if l.is_blocked) / total
        if block_rate > 0.85:
            insights.append({
                "level":   "success",
                "title":   "Block rate excellent",
                "message": f"{round(block_rate*100)}% of intrusions were blocked automatically.",
            })

        return insights

    @staticmethod
    def severity_trend(logs: list) -> dict:
        """
        Breakdown of severity counts — for stacked bar chart.
        Grouped by hour for the last 24 hours.
        """
        buckets = defaultdict(lambda: {"critical": 0, "high": 0, "medium": 0, "low": 0})
        for l in logs:
            h = l.timestamp.strftime("%H:00")
            sev = l.severity if l.severity in ("critical","high","medium","low") else "low"
            buckets[h][sev] += 1
        return dict(sorted(buckets.items()))


# ══════════════════════════════════════════════════════════════════
# MODULE 6 — DASHBOARD MODULE
# Flask routes that serve the HTML and JSON API endpoints
# ══════════════════════════════════════════════════════════════════

# ── Page Routes ─────────────────────────────────────────────────

@app.route("/")
@app.route("/dashboard")
def dashboard():
    """Dashboard homepage."""
    return render_template("dashboard.html")


@app.route("/analysis")
def analysis():
    """Intrusion Analysis page — the main page from your HTML."""
    return render_template("intrusion_analysis.html")


@app.route("/logs")
def logs():
    return render_template("attack_logs.html")


@app.route("/alerts")
def alerts():
    return render_template("alerts.html")


@app.route("/IPmonitor")
def ip_monitor():
    return render_template("ip_monitor.html")


@app.route("/reports")
def reports():
    return render_template("reports.html")


@app.route("/settings")
def settings():
    return render_template("settings.html")


# ── Honeypot catch-all ───────────────────────────────────────────

@app.route("/wp-admin", methods=["GET", "POST"])
@app.route("/wp-login.php", methods=["GET", "POST"])
@app.route("/admin", methods=["GET", "POST"])
@app.route("/login", methods=["GET", "POST"])
@app.route("/.env")
@app.route("/shell.php", methods=["GET", "POST"])
@app.route("/backup.zip")
@app.route("/config.php")
def honeypot_http_trap():
    """
    Flask-level HTTP honeypot traps.
    Any hit is captured, logged, and analysed.
    """
    capture_data = RequestCapture.capture_from_flask_request(request)
    capture_data["service"] = "HTTP-Trap"

    with app.app_context():
        if not DatabaseManager.is_blocked(capture_data["ip_address"]):
            log = IntrusionLogger.log(capture_data)
            AlertGenerator.evaluate(log)

    # Return a convincing fake page to keep the attacker engaged
    return (
        "<html><body><h1>403 Forbidden</h1><p>You don't have permission to access this resource.</p></body></html>",
        403,
    )


# ── JSON API Endpoints (consumed by the frontend JS) ────────────

@app.route("/api/analysis/summary")
def api_summary():
    """Stat card data + risk score."""
    hours = request.args.get("hours", 24, type=int)
    data  = IntrusionAnalyzer.get_summary(hours)
    data["risk_label"] = IntrusionAnalyzer.get_risk_label(data["risk_score"])
    return jsonify(data)


@app.route("/api/analysis/timeline")
def api_timeline():
    """Recent attack events for the timeline panel."""
    hours = request.args.get("hours", 24, type=int)
    limit = request.args.get("limit", 12, type=int)
    logs  = DatabaseManager.get_logs_last_hours(hours)
    return jsonify(IntrusionAnalyzer.recent_events(logs, limit))


@app.route("/api/analysis/distribution")
def api_distribution():
    """Threat type breakdown for donut chart."""
    hours = request.args.get("hours", 24, type=int)
    logs  = DatabaseManager.get_logs_last_hours(hours)
    return jsonify(IntrusionAnalyzer.threat_type_distribution(logs))


@app.route("/api/analysis/top-ips")
def api_top_ips():
    """Top attacker IPs for the table."""
    hours = request.args.get("hours", 24, type=int)
    limit = request.args.get("limit", 10, type=int)
    logs  = DatabaseManager.get_logs_last_hours(hours)
    return jsonify(IntrusionAnalyzer.top_attacker_ips(logs, limit))


@app.route("/api/analysis/heatmap")
def api_heatmap():
    """24-hour activity heatmap data."""
    logs = DatabaseManager.get_logs_last_hours(24)
    return jsonify(IntrusionAnalyzer.hourly_heatmap(logs))


@app.route("/api/analysis/patterns")
def api_patterns():
    """Detected behavioural patterns / insights."""
    hours = request.args.get("hours", 24, type=int)
    logs  = DatabaseManager.get_logs_last_hours(hours)
    return jsonify(IntrusionAnalyzer.detect_patterns(logs))


@app.route("/api/analysis/severity-trend")
def api_severity_trend():
    """Severity trend over 24 hours for stacked chart."""
    logs = DatabaseManager.get_logs_last_hours(24)
    return jsonify(IntrusionAnalyzer.severity_trend(logs))


@app.route("/api/alerts")
def api_alerts():
    """All unread alerts."""
    alerts = DatabaseManager.get_unread_alerts()
    return jsonify([a.to_dict() for a in alerts])


@app.route("/api/alerts/<int:alert_id>/read", methods=["POST"])
def api_mark_alert_read(alert_id):
    DatabaseManager.mark_alert_read(alert_id)
    return jsonify({"status": "ok"})


@app.route("/api/block-ip", methods=["POST"])
def api_block_ip():
    """Admin manually blocks an IP."""
    data = request.get_json()
    ip   = data.get("ip")
    if not ip:
        return jsonify({"error": "IP required"}), 400
    DatabaseManager.block_ip(ip, reason=data.get("reason", "Manual block"), by="admin")
    return jsonify({"status": "blocked", "ip": ip})


@app.route("/api/logs")
def api_logs():
    """Paginated log list."""
    page     = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 20, type=int)
    logs     = IntrusionLog.query.order_by(IntrusionLog.timestamp.desc())\
                   .paginate(page=page, per_page=per_page, error_out=False)
    return jsonify({
        "total":    logs.total,
        "page":     logs.page,
        "pages":    logs.pages,
        "logs":     [l.to_dict() for l in logs.items],
    })


@app.route("/api/logs/<int:log_id>", methods=["DELETE"])
def api_delete_log(log_id):
    if DatabaseManager.delete_log(log_id):
        return jsonify({"status": "deleted"})
    return jsonify({"error": "Not found"}), 404


# ── Seed Demo Data ───────────────────────────────────────────────

def seed_demo_data():
    """
    Insert realistic demo intrusion records so the dashboard
    shows data immediately without real attacker traffic.
    Only runs if the DB is empty.
    """
    if IntrusionLog.query.count() > 0:
        return

    demo_events = [
        # (ip, port, service, path, payload, method, country, hours_ago)
        ("91.134.22.87",  80, "HTTP", "/login?id=1 OR 1=1--",      "' OR 1=1--",              "GET",  "France",      0.2),
        ("185.220.101.4", 80, "HTTP", "/admin/login",               "user=admin&pass=admin123","POST", "Germany",     0.5),
        ("45.83.65.198",  80, "HTTP", "/wp-admin",                  "",                        "GET",  "Netherlands", 0.8),
        ("193.32.127.1",  80, "HTTP", "/../../../etc/passwd",       "",                        "GET",  "Russia",      1.0),
        ("77.111.240.5",  80, "HTTP", "/cmd?exec=/bin/bash",        "exec(/bin/bash)",         "POST", "Ukraine",     1.2),
        ("162.55.36.211", 80, "HTTP", "/.env",                      "",                        "GET",  "Germany",     1.5),
        ("91.134.22.87",  80, "HTTP", "/api/auth/token",            "user=admin&pass=test",    "POST", "France",      2.0),
        ("45.83.65.198",  80, "HTTP", "/backup.zip",                "",                        "GET",  "Netherlands", 2.3),
        ("104.21.9.208",  80, "HTTP", "/.git/config",               "",                        "GET",  "USA",         2.5),
        ("185.220.101.4", 22, "SSH",  "/ssh",                       "SSH handshake",           "CONN", "Germany",     3.0),
        ("91.134.22.87",  80, "HTTP", "/checkout?id=1;DROP TABLE",  "'; DROP TABLE users--",   "POST", "France",      3.5),
        ("193.32.127.1",  80, "HTTP", "/upload",                    "wget malware.sh|bash",    "POST", "Russia",      4.0),
        ("77.111.240.5",  80, "HTTP", "/shell.php",                 "cmd.php shell upload",    "POST", "Ukraine",     4.2),
        ("162.55.36.211", 80, "HTTP", "/search?q=<script>alert(1)","<script>alert(1)</script>","GET",  "Germany",     5.0),
        ("45.83.65.198",  80, "HTTP", "/wp-login.php",              "log=admin&pwd=password",  "POST", "Netherlands", 5.5),
        ("104.21.9.208",  80, "HTTP", "/phpinfo.php",               "",                        "GET",  "USA",         6.0),
        ("91.134.22.87",  80, "HTTP", "/api/users?id=1 UNION SELECT","UNION SELECT * FROM",    "GET",  "France",      6.5),
        ("185.220.101.4", 80, "HTTP", "/admin/config",              "../../etc/shadow",        "GET",  "Germany",     7.0),
        ("193.32.127.1",  80, "HTTP", "/login",                     "user=root&pass=toor",     "POST", "Russia",      8.0),
        ("45.83.65.198",  80, "HTTP", "/config.php",                "",                        "GET",  "Netherlands", 9.0),
    ]

    # Add extra volume for realistic heatmap (spread across 24 hours)
    bulk_ips   = ["91.134.22.87","185.220.101.4","45.83.65.198","193.32.127.1","77.111.240.5"]
    bulk_paths = ["/login","/admin","/wp-admin","/.env","/api/users"]
    for h in range(24):
        count = random.randint(2, 20)
        for _ in range(count):
            ip   = random.choice(bulk_ips)
            path = random.choice(bulk_paths)
            threat, severity = RequestCapture.classify_threat(path, "")
            ts = datetime.utcnow() - timedelta(hours=h, minutes=random.randint(0, 59))
            log = IntrusionLog(
                ip_address=ip, port=80, service="HTTP", method="GET",
                path=path, payload=None, country="Unknown",
                threat_type=threat, severity=severity,
                action_taken="Blocked" if severity == "critical" else "Logged",
                is_blocked=severity == "critical",
                timestamp=ts,
            )
            db.session.add(log)

    # Insert the detailed demo events
    for ip, port, service, path, payload, method, country, hours_ago in demo_events:
        threat, severity = RequestCapture.classify_threat(path, payload)
        ts = datetime.utcnow() - timedelta(hours=hours_ago)
        log = IntrusionLog(
            ip_address=ip, port=port, service=service,
            method=method, path=path, payload=payload, country=country,
            threat_type=threat, severity=severity,
            action_taken="Blocked" if severity == "critical" else "Alerted",
            is_blocked=severity == "critical",
            timestamp=ts,
        )
        db.session.add(log)

    db.session.commit()
    print("[SEED] Demo intrusion data inserted.")

    # Generate a few starter alerts
    for ip in ["91.134.22.87", "193.32.127.1", "77.111.240.5"]:
        DatabaseManager.insert_alert({
            "title":       f"Critical threat — {ip}",
            "description": f"Multiple critical events detected from {ip}. Auto-analysis flagged this IP.",
            "ip_address":  ip,
            "severity":    "critical",
            "threat_type": "SQL Injection",
        })
    print("[SEED] Demo alerts inserted.")


# ══════════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    with app.app_context():
        # Create all tables
        db.create_all()
        print("[DB] Tables created / verified.")

        # Insert demo data if DB is empty
        seed_demo_data()

    # Start honeypot listeners in background
    # (comment out if you don't want actual port listeners)
    honeypot = HoneypotService(host="0.0.0.0")
    # honeypot.start(ssh_port=2222, http_port=8080)  # uncomment to activate

    # Launch Flask
    print("[HONEYSHIELD] Starting on http://localhost:5000")
    app.run(debug=True, host="0.0.0.0", port=5000, use_reloader=False)
